spring.application.name=seperate-db

# Database Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/seperate_db
#spring.datasource.username=seperate_db
#spring.datasource.password=seperate_db
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect