data.key-values.key1=Dev Value 1
data.key-values.key2=Dev Value 2
data.key-values.key3=Dev Value 3

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tenant1db
spring.datasource.username=tenant1user
spring.datasource.password=tenant1pass
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
logging.level.com.zaxxer.hikari=DEBUG


# Hibernate
spring.jpa.show-sql=true

# Actuator metrics
management.endpoints.web.exposure.include=metrics,health
management.endpoint.metrics.enabled=true
