spring.application.name=shared-db-shared-tenant

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/same_schema_and_db
spring.datasource.username=same_schema_and_db
spring.datasource.password=same_schema_and_db
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect