spring.application.name=schema-per-tenant


# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/schema_per_tenant
spring.datasource.username=schema_per_tenant
spring.datasource.password=schema_per_tenant
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect